language: minimal

services:
  - docker

before_install:
  - docker -v && docker-compose -v
  - docker-compose -f ./docker-compose-build.yaml build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quangtran3519/reverseproxy:v1
  - docker push quangtran3519/udagram-api-user:v1
  - docker push quangtran3519/udagram-api-feed:v1
  - docker push quangtran3519/udagram-frontend:v1
